from repo_analysis_tools.core.errors import ErrorCode
from repo_analysis_tools.mcp.contracts.common import ToolContract


QUERY_CONTRACTS = (
    ToolContract(
        name="list_priority_files",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>"},
        output_schema={"files": "list"},
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("get_file_info", "list_file_symbols"),
    ),
    ToolContract(
        name="get_file_info",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>", "path": "string"},
        output_schema={
            "path": "string",
            "role": "string",
            "priority_score": "int",
            "line_count": "int",
            "symbol_count": "int",
            "function_count": "int",
            "type_count": "int",
            "macro_count": "int",
            "include_count": "int",
            "incoming_call_count": "int",
            "outgoing_call_count": "int",
            "root_function_count": "int",
            "has_main_definition": "bool",
        },
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("list_file_symbols", "find_root_functions"),
    ),
    ToolContract(
        name="list_file_symbols",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>", "paths": "list[string]"},
        output_schema={"files": "list"},
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("open_symbol_context", "resolve_symbols"),
    ),
    ToolContract(
        name="resolve_symbols",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>", "symbol_name": "string"},
        output_schema={"match_count": "int", "matches": "list"},
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("open_symbol_context", "query_call_relations"),
    ),
    ToolContract(
        name="open_symbol_context",
        domain="query",
        input_schema={
            "scan_id": "scan_<12-hex>",
            "symbol_id": "string",
            "context_lines": "int",
        },
        output_schema={
            "symbol_id": "string",
            "name": "string",
            "kind": "string",
            "path": "string",
            "definition_line_start": "int",
            "definition_line_end": "int",
            "context_line_start": "int",
            "context_line_end": "int",
            "lines": "list[string]",
        },
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("query_call_relations", "find_call_paths"),
    ),
    ToolContract(
        name="query_call_relations",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>", "function_id": "string"},
        output_schema={
            "callers": "list",
            "callees": "list",
            "non_resolved_callees": "list",
        },
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("find_call_paths", "find_root_functions"),
    ),
    ToolContract(
        name="find_root_functions",
        domain="query",
        input_schema={"scan_id": "scan_<12-hex>", "paths": "list[string]"},
        output_schema={"roots": "list"},
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("find_call_paths", "open_symbol_context"),
    ),
    ToolContract(
        name="find_call_paths",
        domain="query",
        input_schema={
            "scan_id": "scan_<12-hex>",
            "from_function_id": "string",
            "to_function_id": "string",
        },
        output_schema={
            "status": "string",
            "returned_path_count": "int",
            "truncated": "bool",
            "paths": "list",
        },
        stable_ids=(),
        failure_modes=(ErrorCode.INVALID_INPUT, ErrorCode.NOT_FOUND, ErrorCode.INTERNAL),
        recommended_next_tools=("open_symbol_context", "query_call_relations"),
    ),
)
